// Code generated by Kitex v0.15.2. DO NOT EDIT.

package todoservice

import (
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
	todo "todo-list/kitex_gen/todo"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	AddTodo(ctx context.Context, request *todo.AddTodoRequest, callOptions ...callopt.Option) (r *todo.AddTodoResponse, err error)
	DeleteTodo(ctx context.Context, request *todo.DeleteTodoRequest, callOptions ...callopt.Option) (r *todo.DeleteTodoResponse, err error)
	UpdateTodo(ctx context.Context, request *todo.UpdateTodoRequest, callOptions ...callopt.Option) (r *todo.UpdateTodoResponse, err error)
	GetTodo(ctx context.Context, request *todo.GetTodoRequest, callOptions ...callopt.Option) (r *todo.GetTodoResponse, err error)
	ListTodo(ctx context.Context, request *todo.ListTodoRequest, callOptions ...callopt.Option) (r *todo.ListTodoResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kTodoServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kTodoServiceClient struct {
	*kClient
}

func (p *kTodoServiceClient) AddTodo(ctx context.Context, request *todo.AddTodoRequest, callOptions ...callopt.Option) (r *todo.AddTodoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.AddTodo(ctx, request)
}

func (p *kTodoServiceClient) DeleteTodo(ctx context.Context, request *todo.DeleteTodoRequest, callOptions ...callopt.Option) (r *todo.DeleteTodoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteTodo(ctx, request)
}

func (p *kTodoServiceClient) UpdateTodo(ctx context.Context, request *todo.UpdateTodoRequest, callOptions ...callopt.Option) (r *todo.UpdateTodoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateTodo(ctx, request)
}

func (p *kTodoServiceClient) GetTodo(ctx context.Context, request *todo.GetTodoRequest, callOptions ...callopt.Option) (r *todo.GetTodoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetTodo(ctx, request)
}

func (p *kTodoServiceClient) ListTodo(ctx context.Context, request *todo.ListTodoRequest, callOptions ...callopt.Option) (r *todo.ListTodoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.ListTodo(ctx, request)
}
