// Code generated by Kitex v0.15.2. DO NOT EDIT.

package todoservice

import (
	"context"
	"errors"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	todo "todo-list/kitex_gen/todo"
)

var errInvalidMessageType = errors.New("invalid message type for service method handler")

var serviceMethods = map[string]kitex.MethodInfo{
	"AddTodo": kitex.NewMethodInfo(
		addTodoHandler,
		newTodoServiceAddTodoArgs,
		newTodoServiceAddTodoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"DeleteTodo": kitex.NewMethodInfo(
		deleteTodoHandler,
		newTodoServiceDeleteTodoArgs,
		newTodoServiceDeleteTodoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"UpdateTodo": kitex.NewMethodInfo(
		updateTodoHandler,
		newTodoServiceUpdateTodoArgs,
		newTodoServiceUpdateTodoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"GetTodo": kitex.NewMethodInfo(
		getTodoHandler,
		newTodoServiceGetTodoArgs,
		newTodoServiceGetTodoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
	"ListTodo": kitex.NewMethodInfo(
		listTodoHandler,
		newTodoServiceListTodoArgs,
		newTodoServiceListTodoResult,
		false,
		kitex.WithStreamingMode(kitex.StreamingNone),
	),
}

var (
	todoServiceServiceInfo                = NewServiceInfo()
	todoServiceServiceInfoForClient       = NewServiceInfoForClient()
	todoServiceServiceInfoForStreamClient = NewServiceInfoForStreamClient()
)

// for server
func serviceInfo() *kitex.ServiceInfo {
	return todoServiceServiceInfo
}

// for stream client
func serviceInfoForStreamClient() *kitex.ServiceInfo {
	return todoServiceServiceInfoForStreamClient
}

// for client
func serviceInfoForClient() *kitex.ServiceInfo {
	return todoServiceServiceInfoForClient
}

// NewServiceInfo creates a new ServiceInfo containing all methods
func NewServiceInfo() *kitex.ServiceInfo {
	return newServiceInfo(false, true, true)
}

// NewServiceInfo creates a new ServiceInfo containing non-streaming methods
func NewServiceInfoForClient() *kitex.ServiceInfo {
	return newServiceInfo(false, false, true)
}
func NewServiceInfoForStreamClient() *kitex.ServiceInfo {
	return newServiceInfo(true, true, false)
}

func newServiceInfo(hasStreaming bool, keepStreamingMethods bool, keepNonStreamingMethods bool) *kitex.ServiceInfo {
	serviceName := "TodoService"
	handlerType := (*todo.TodoService)(nil)
	methods := map[string]kitex.MethodInfo{}
	for name, m := range serviceMethods {
		if m.IsStreaming() && !keepStreamingMethods {
			continue
		}
		if !m.IsStreaming() && !keepNonStreamingMethods {
			continue
		}
		methods[name] = m
	}
	extra := map[string]interface{}{
		"PackageName": "todo",
	}
	if hasStreaming {
		extra["streaming"] = hasStreaming
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.15.2",
		Extra:           extra,
	}
	return svcInfo
}

func addTodoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*todo.TodoServiceAddTodoArgs)
	realResult := result.(*todo.TodoServiceAddTodoResult)
	success, err := handler.(todo.TodoService).AddTodo(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTodoServiceAddTodoArgs() interface{} {
	return todo.NewTodoServiceAddTodoArgs()
}

func newTodoServiceAddTodoResult() interface{} {
	return todo.NewTodoServiceAddTodoResult()
}

func deleteTodoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*todo.TodoServiceDeleteTodoArgs)
	realResult := result.(*todo.TodoServiceDeleteTodoResult)
	success, err := handler.(todo.TodoService).DeleteTodo(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTodoServiceDeleteTodoArgs() interface{} {
	return todo.NewTodoServiceDeleteTodoArgs()
}

func newTodoServiceDeleteTodoResult() interface{} {
	return todo.NewTodoServiceDeleteTodoResult()
}

func updateTodoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*todo.TodoServiceUpdateTodoArgs)
	realResult := result.(*todo.TodoServiceUpdateTodoResult)
	success, err := handler.(todo.TodoService).UpdateTodo(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTodoServiceUpdateTodoArgs() interface{} {
	return todo.NewTodoServiceUpdateTodoArgs()
}

func newTodoServiceUpdateTodoResult() interface{} {
	return todo.NewTodoServiceUpdateTodoResult()
}

func getTodoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*todo.TodoServiceGetTodoArgs)
	realResult := result.(*todo.TodoServiceGetTodoResult)
	success, err := handler.(todo.TodoService).GetTodo(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTodoServiceGetTodoArgs() interface{} {
	return todo.NewTodoServiceGetTodoArgs()
}

func newTodoServiceGetTodoResult() interface{} {
	return todo.NewTodoServiceGetTodoResult()
}

func listTodoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*todo.TodoServiceListTodoArgs)
	realResult := result.(*todo.TodoServiceListTodoResult)
	success, err := handler.(todo.TodoService).ListTodo(ctx, realArg.Request)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newTodoServiceListTodoArgs() interface{} {
	return todo.NewTodoServiceListTodoArgs()
}

func newTodoServiceListTodoResult() interface{} {
	return todo.NewTodoServiceListTodoResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) AddTodo(ctx context.Context, request *todo.AddTodoRequest) (r *todo.AddTodoResponse, err error) {
	var _args todo.TodoServiceAddTodoArgs
	_args.Request = request
	var _result todo.TodoServiceAddTodoResult
	if err = p.c.Call(ctx, "AddTodo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) DeleteTodo(ctx context.Context, request *todo.DeleteTodoRequest) (r *todo.DeleteTodoResponse, err error) {
	var _args todo.TodoServiceDeleteTodoArgs
	_args.Request = request
	var _result todo.TodoServiceDeleteTodoResult
	if err = p.c.Call(ctx, "DeleteTodo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) UpdateTodo(ctx context.Context, request *todo.UpdateTodoRequest) (r *todo.UpdateTodoResponse, err error) {
	var _args todo.TodoServiceUpdateTodoArgs
	_args.Request = request
	var _result todo.TodoServiceUpdateTodoResult
	if err = p.c.Call(ctx, "UpdateTodo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetTodo(ctx context.Context, request *todo.GetTodoRequest) (r *todo.GetTodoResponse, err error) {
	var _args todo.TodoServiceGetTodoArgs
	_args.Request = request
	var _result todo.TodoServiceGetTodoResult
	if err = p.c.Call(ctx, "GetTodo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) ListTodo(ctx context.Context, request *todo.ListTodoRequest) (r *todo.ListTodoResponse, err error) {
	var _args todo.TodoServiceListTodoArgs
	_args.Request = request
	var _result todo.TodoServiceListTodoResult
	if err = p.c.Call(ctx, "ListTodo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
