// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package model

import (
	"fmt"
)

type RespBase struct {
	Code    int32  `thrift:"code,1" frugal:"1,default,i32" json:"code"`
	Message string `thrift:"message,2" frugal:"2,default,string" json:"message"`
}

func NewRespBase() *RespBase {
	return &RespBase{}
}

func (p *RespBase) InitDefault() {
}

func (p *RespBase) GetCode() (v int32) {
	return p.Code
}

func (p *RespBase) GetMessage() (v string) {
	return p.Message
}
func (p *RespBase) SetCode(val int32) {
	p.Code = val
}
func (p *RespBase) SetMessage(val string) {
	p.Message = val
}

func (p *RespBase) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RespBase(%+v)", *p)
}

var fieldIDToName_RespBase = map[int16]string{
	1: "code",
	2: "message",
}

type UserInfo struct {
	UserId int64  `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
	Name   string `thrift:"name,2" frugal:"2,default,string" json:"name"`
}

func NewUserInfo() *UserInfo {
	return &UserInfo{}
}

func (p *UserInfo) InitDefault() {
}

func (p *UserInfo) GetUserId() (v int64) {
	return p.UserId
}

func (p *UserInfo) GetName() (v string) {
	return p.Name
}
func (p *UserInfo) SetUserId(val int64) {
	p.UserId = val
}
func (p *UserInfo) SetName(val string) {
	p.Name = val
}

func (p *UserInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserInfo(%+v)", *p)
}

var fieldIDToName_UserInfo = map[int16]string{
	1: "userId",
	2: "name",
}
