// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package todo

import (
	"context"
	"fmt"
	"todo-list/kitex_gen/model"
)

type Todo struct {
	Id        int64  `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Title     string `thrift:"title,2" frugal:"2,default,string" json:"title"`
	Content   string `thrift:"content,3" frugal:"3,default,string" json:"content"`
	Completed bool   `thrift:"completed,4" frugal:"4,default,bool" json:"completed"`
	UserId    int64  `thrift:"userId,5" frugal:"5,default,i64" json:"userId"`
	CreatedAt string `thrift:"createdAt,6" frugal:"6,default,string" json:"createdAt"`
	DiedAt    string `thrift:"diedAt,7" frugal:"7,default,string" json:"diedAt"`
	Priority  int64  `thrift:"priority,8" frugal:"8,default,i64" json:"priority"`
}

func NewTodo() *Todo {
	return &Todo{}
}

func (p *Todo) InitDefault() {
}

func (p *Todo) GetId() (v int64) {
	return p.Id
}

func (p *Todo) GetTitle() (v string) {
	return p.Title
}

func (p *Todo) GetContent() (v string) {
	return p.Content
}

func (p *Todo) GetCompleted() (v bool) {
	return p.Completed
}

func (p *Todo) GetUserId() (v int64) {
	return p.UserId
}

func (p *Todo) GetCreatedAt() (v string) {
	return p.CreatedAt
}

func (p *Todo) GetDiedAt() (v string) {
	return p.DiedAt
}

func (p *Todo) GetPriority() (v int64) {
	return p.Priority
}
func (p *Todo) SetId(val int64) {
	p.Id = val
}
func (p *Todo) SetTitle(val string) {
	p.Title = val
}
func (p *Todo) SetContent(val string) {
	p.Content = val
}
func (p *Todo) SetCompleted(val bool) {
	p.Completed = val
}
func (p *Todo) SetUserId(val int64) {
	p.UserId = val
}
func (p *Todo) SetCreatedAt(val string) {
	p.CreatedAt = val
}
func (p *Todo) SetDiedAt(val string) {
	p.DiedAt = val
}
func (p *Todo) SetPriority(val int64) {
	p.Priority = val
}

func (p *Todo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("Todo(%+v)", *p)
}

var fieldIDToName_Todo = map[int16]string{
	1: "id",
	2: "title",
	3: "content",
	4: "completed",
	5: "userId",
	6: "createdAt",
	7: "diedAt",
	8: "priority",
}

type AddTodoRequest struct {
	Title    string `thrift:"title,1" frugal:"1,default,string" json:"title"`
	Content  string `thrift:"content,2" frugal:"2,default,string" json:"content"`
	UserId   int64  `thrift:"userId,3" frugal:"3,default,i64" json:"userId"`
	DiedAt   string `thrift:"diedAt,4" frugal:"4,default,string" json:"diedAt"`
	Priority int64  `thrift:"priority,5" frugal:"5,default,i64" json:"priority"`
}

func NewAddTodoRequest() *AddTodoRequest {
	return &AddTodoRequest{}
}

func (p *AddTodoRequest) InitDefault() {
}

func (p *AddTodoRequest) GetTitle() (v string) {
	return p.Title
}

func (p *AddTodoRequest) GetContent() (v string) {
	return p.Content
}

func (p *AddTodoRequest) GetUserId() (v int64) {
	return p.UserId
}

func (p *AddTodoRequest) GetDiedAt() (v string) {
	return p.DiedAt
}

func (p *AddTodoRequest) GetPriority() (v int64) {
	return p.Priority
}
func (p *AddTodoRequest) SetTitle(val string) {
	p.Title = val
}
func (p *AddTodoRequest) SetContent(val string) {
	p.Content = val
}
func (p *AddTodoRequest) SetUserId(val int64) {
	p.UserId = val
}
func (p *AddTodoRequest) SetDiedAt(val string) {
	p.DiedAt = val
}
func (p *AddTodoRequest) SetPriority(val int64) {
	p.Priority = val
}

func (p *AddTodoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddTodoRequest(%+v)", *p)
}

var fieldIDToName_AddTodoRequest = map[int16]string{
	1: "title",
	2: "content",
	3: "userId",
	4: "diedAt",
	5: "priority",
}

type AddTodoResponse struct {
	Id   int64           `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Base *model.RespBase `thrift:"base,2" frugal:"2,default,model.RespBase" json:"base"`
}

func NewAddTodoResponse() *AddTodoResponse {
	return &AddTodoResponse{}
}

func (p *AddTodoResponse) InitDefault() {
}

func (p *AddTodoResponse) GetId() (v int64) {
	return p.Id
}

var AddTodoResponse_Base_DEFAULT *model.RespBase

func (p *AddTodoResponse) GetBase() (v *model.RespBase) {
	if !p.IsSetBase() {
		return AddTodoResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *AddTodoResponse) SetId(val int64) {
	p.Id = val
}
func (p *AddTodoResponse) SetBase(val *model.RespBase) {
	p.Base = val
}

func (p *AddTodoResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *AddTodoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("AddTodoResponse(%+v)", *p)
}

var fieldIDToName_AddTodoResponse = map[int16]string{
	1: "id",
	2: "base",
}

type DeleteTodoRequest struct {
	Id int64 `thrift:"id,1" frugal:"1,default,i64" json:"id"`
}

func NewDeleteTodoRequest() *DeleteTodoRequest {
	return &DeleteTodoRequest{}
}

func (p *DeleteTodoRequest) InitDefault() {
}

func (p *DeleteTodoRequest) GetId() (v int64) {
	return p.Id
}
func (p *DeleteTodoRequest) SetId(val int64) {
	p.Id = val
}

func (p *DeleteTodoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteTodoRequest(%+v)", *p)
}

var fieldIDToName_DeleteTodoRequest = map[int16]string{
	1: "id",
}

type DeleteTodoResponse struct {
	Success bool            `thrift:"success,1" frugal:"1,default,bool" json:"success"`
	Base    *model.RespBase `thrift:"base,2" frugal:"2,default,model.RespBase" json:"base"`
}

func NewDeleteTodoResponse() *DeleteTodoResponse {
	return &DeleteTodoResponse{}
}

func (p *DeleteTodoResponse) InitDefault() {
}

func (p *DeleteTodoResponse) GetSuccess() (v bool) {
	return p.Success
}

var DeleteTodoResponse_Base_DEFAULT *model.RespBase

func (p *DeleteTodoResponse) GetBase() (v *model.RespBase) {
	if !p.IsSetBase() {
		return DeleteTodoResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *DeleteTodoResponse) SetSuccess(val bool) {
	p.Success = val
}
func (p *DeleteTodoResponse) SetBase(val *model.RespBase) {
	p.Base = val
}

func (p *DeleteTodoResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *DeleteTodoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("DeleteTodoResponse(%+v)", *p)
}

var fieldIDToName_DeleteTodoResponse = map[int16]string{
	1: "success",
	2: "base",
}

type UpdateTodoRequest struct {
	Id        int64   `thrift:"id,1" frugal:"1,default,i64" json:"id"`
	Title     *string `thrift:"title,2,optional" frugal:"2,optional,string" json:"title,omitempty"`
	Content   *string `thrift:"content,3,optional" frugal:"3,optional,string" json:"content,omitempty"`
	Completed *bool   `thrift:"completed,4,optional" frugal:"4,optional,bool" json:"completed,omitempty"`
	DiedAt    *string `thrift:"diedAt,5,optional" frugal:"5,optional,string" json:"diedAt,omitempty"`
	Priority  *int64  `thrift:"priority,6,optional" frugal:"6,optional,i64" json:"priority,omitempty"`
}

func NewUpdateTodoRequest() *UpdateTodoRequest {
	return &UpdateTodoRequest{}
}

func (p *UpdateTodoRequest) InitDefault() {
}

func (p *UpdateTodoRequest) GetId() (v int64) {
	return p.Id
}

var UpdateTodoRequest_Title_DEFAULT string

func (p *UpdateTodoRequest) GetTitle() (v string) {
	if !p.IsSetTitle() {
		return UpdateTodoRequest_Title_DEFAULT
	}
	return *p.Title
}

var UpdateTodoRequest_Content_DEFAULT string

func (p *UpdateTodoRequest) GetContent() (v string) {
	if !p.IsSetContent() {
		return UpdateTodoRequest_Content_DEFAULT
	}
	return *p.Content
}

var UpdateTodoRequest_Completed_DEFAULT bool

func (p *UpdateTodoRequest) GetCompleted() (v bool) {
	if !p.IsSetCompleted() {
		return UpdateTodoRequest_Completed_DEFAULT
	}
	return *p.Completed
}

var UpdateTodoRequest_DiedAt_DEFAULT string

func (p *UpdateTodoRequest) GetDiedAt() (v string) {
	if !p.IsSetDiedAt() {
		return UpdateTodoRequest_DiedAt_DEFAULT
	}
	return *p.DiedAt
}

var UpdateTodoRequest_Priority_DEFAULT int64

func (p *UpdateTodoRequest) GetPriority() (v int64) {
	if !p.IsSetPriority() {
		return UpdateTodoRequest_Priority_DEFAULT
	}
	return *p.Priority
}
func (p *UpdateTodoRequest) SetId(val int64) {
	p.Id = val
}
func (p *UpdateTodoRequest) SetTitle(val *string) {
	p.Title = val
}
func (p *UpdateTodoRequest) SetContent(val *string) {
	p.Content = val
}
func (p *UpdateTodoRequest) SetCompleted(val *bool) {
	p.Completed = val
}
func (p *UpdateTodoRequest) SetDiedAt(val *string) {
	p.DiedAt = val
}
func (p *UpdateTodoRequest) SetPriority(val *int64) {
	p.Priority = val
}

func (p *UpdateTodoRequest) IsSetTitle() bool {
	return p.Title != nil
}

func (p *UpdateTodoRequest) IsSetContent() bool {
	return p.Content != nil
}

func (p *UpdateTodoRequest) IsSetCompleted() bool {
	return p.Completed != nil
}

func (p *UpdateTodoRequest) IsSetDiedAt() bool {
	return p.DiedAt != nil
}

func (p *UpdateTodoRequest) IsSetPriority() bool {
	return p.Priority != nil
}

func (p *UpdateTodoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateTodoRequest(%+v)", *p)
}

var fieldIDToName_UpdateTodoRequest = map[int16]string{
	1: "id",
	2: "title",
	3: "content",
	4: "completed",
	5: "diedAt",
	6: "priority",
}

type UpdateTodoResponse struct {
	Base *model.RespBase `thrift:"base,1" frugal:"1,default,model.RespBase" json:"base"`
}

func NewUpdateTodoResponse() *UpdateTodoResponse {
	return &UpdateTodoResponse{}
}

func (p *UpdateTodoResponse) InitDefault() {
}

var UpdateTodoResponse_Base_DEFAULT *model.RespBase

func (p *UpdateTodoResponse) GetBase() (v *model.RespBase) {
	if !p.IsSetBase() {
		return UpdateTodoResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *UpdateTodoResponse) SetBase(val *model.RespBase) {
	p.Base = val
}

func (p *UpdateTodoResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpdateTodoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateTodoResponse(%+v)", *p)
}

var fieldIDToName_UpdateTodoResponse = map[int16]string{
	1: "base",
}

type GetTodoRequest struct {
	Id int64 `thrift:"id,1" frugal:"1,default,i64" json:"id"`
}

func NewGetTodoRequest() *GetTodoRequest {
	return &GetTodoRequest{}
}

func (p *GetTodoRequest) InitDefault() {
}

func (p *GetTodoRequest) GetId() (v int64) {
	return p.Id
}
func (p *GetTodoRequest) SetId(val int64) {
	p.Id = val
}

func (p *GetTodoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTodoRequest(%+v)", *p)
}

var fieldIDToName_GetTodoRequest = map[int16]string{
	1: "id",
}

type GetTodoResponse struct {
	Todo *Todo           `thrift:"todo,1" frugal:"1,default,Todo" json:"todo"`
	Base *model.RespBase `thrift:"base,2" frugal:"2,default,model.RespBase" json:"base"`
}

func NewGetTodoResponse() *GetTodoResponse {
	return &GetTodoResponse{}
}

func (p *GetTodoResponse) InitDefault() {
}

var GetTodoResponse_Todo_DEFAULT *Todo

func (p *GetTodoResponse) GetTodo() (v *Todo) {
	if !p.IsSetTodo() {
		return GetTodoResponse_Todo_DEFAULT
	}
	return p.Todo
}

var GetTodoResponse_Base_DEFAULT *model.RespBase

func (p *GetTodoResponse) GetBase() (v *model.RespBase) {
	if !p.IsSetBase() {
		return GetTodoResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *GetTodoResponse) SetTodo(val *Todo) {
	p.Todo = val
}
func (p *GetTodoResponse) SetBase(val *model.RespBase) {
	p.Base = val
}

func (p *GetTodoResponse) IsSetTodo() bool {
	return p.Todo != nil
}

func (p *GetTodoResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetTodoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetTodoResponse(%+v)", *p)
}

var fieldIDToName_GetTodoResponse = map[int16]string{
	1: "todo",
	2: "base",
}

type ListTodoRequest struct {
	UserId int64 `thrift:"userId,1" frugal:"1,default,i64" json:"userId"`
}

func NewListTodoRequest() *ListTodoRequest {
	return &ListTodoRequest{}
}

func (p *ListTodoRequest) InitDefault() {
}

func (p *ListTodoRequest) GetUserId() (v int64) {
	return p.UserId
}
func (p *ListTodoRequest) SetUserId(val int64) {
	p.UserId = val
}

func (p *ListTodoRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListTodoRequest(%+v)", *p)
}

var fieldIDToName_ListTodoRequest = map[int16]string{
	1: "userId",
}

type ListTodoResponse struct {
	Todos []*Todo         `thrift:"todos,1" frugal:"1,default,list<Todo>" json:"todos"`
	Base  *model.RespBase `thrift:"base,2" frugal:"2,default,model.RespBase" json:"base"`
}

func NewListTodoResponse() *ListTodoResponse {
	return &ListTodoResponse{}
}

func (p *ListTodoResponse) InitDefault() {
}

func (p *ListTodoResponse) GetTodos() (v []*Todo) {
	return p.Todos
}

var ListTodoResponse_Base_DEFAULT *model.RespBase

func (p *ListTodoResponse) GetBase() (v *model.RespBase) {
	if !p.IsSetBase() {
		return ListTodoResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *ListTodoResponse) SetTodos(val []*Todo) {
	p.Todos = val
}
func (p *ListTodoResponse) SetBase(val *model.RespBase) {
	p.Base = val
}

func (p *ListTodoResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *ListTodoResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("ListTodoResponse(%+v)", *p)
}

var fieldIDToName_ListTodoResponse = map[int16]string{
	1: "todos",
	2: "base",
}

type TodoService interface {
	AddTodo(ctx context.Context, request *AddTodoRequest) (r *AddTodoResponse, err error)

	DeleteTodo(ctx context.Context, request *DeleteTodoRequest) (r *DeleteTodoResponse, err error)

	UpdateTodo(ctx context.Context, request *UpdateTodoRequest) (r *UpdateTodoResponse, err error)

	GetTodo(ctx context.Context, request *GetTodoRequest) (r *GetTodoResponse, err error)

	ListTodo(ctx context.Context, request *ListTodoRequest) (r *ListTodoResponse, err error)
}

type TodoServiceAddTodoArgs struct {
	Request *AddTodoRequest `thrift:"request,1" frugal:"1,default,AddTodoRequest" json:"request"`
}

func NewTodoServiceAddTodoArgs() *TodoServiceAddTodoArgs {
	return &TodoServiceAddTodoArgs{}
}

func (p *TodoServiceAddTodoArgs) InitDefault() {
}

var TodoServiceAddTodoArgs_Request_DEFAULT *AddTodoRequest

func (p *TodoServiceAddTodoArgs) GetRequest() (v *AddTodoRequest) {
	if !p.IsSetRequest() {
		return TodoServiceAddTodoArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *TodoServiceAddTodoArgs) SetRequest(val *AddTodoRequest) {
	p.Request = val
}

func (p *TodoServiceAddTodoArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *TodoServiceAddTodoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TodoServiceAddTodoArgs(%+v)", *p)
}

var fieldIDToName_TodoServiceAddTodoArgs = map[int16]string{
	1: "request",
}

type TodoServiceAddTodoResult struct {
	Success *AddTodoResponse `thrift:"success,0,optional" frugal:"0,optional,AddTodoResponse" json:"success,omitempty"`
}

func NewTodoServiceAddTodoResult() *TodoServiceAddTodoResult {
	return &TodoServiceAddTodoResult{}
}

func (p *TodoServiceAddTodoResult) InitDefault() {
}

var TodoServiceAddTodoResult_Success_DEFAULT *AddTodoResponse

func (p *TodoServiceAddTodoResult) GetSuccess() (v *AddTodoResponse) {
	if !p.IsSetSuccess() {
		return TodoServiceAddTodoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TodoServiceAddTodoResult) SetSuccess(x interface{}) {
	p.Success = x.(*AddTodoResponse)
}

func (p *TodoServiceAddTodoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TodoServiceAddTodoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TodoServiceAddTodoResult(%+v)", *p)
}

var fieldIDToName_TodoServiceAddTodoResult = map[int16]string{
	0: "success",
}

type TodoServiceDeleteTodoArgs struct {
	Request *DeleteTodoRequest `thrift:"request,1" frugal:"1,default,DeleteTodoRequest" json:"request"`
}

func NewTodoServiceDeleteTodoArgs() *TodoServiceDeleteTodoArgs {
	return &TodoServiceDeleteTodoArgs{}
}

func (p *TodoServiceDeleteTodoArgs) InitDefault() {
}

var TodoServiceDeleteTodoArgs_Request_DEFAULT *DeleteTodoRequest

func (p *TodoServiceDeleteTodoArgs) GetRequest() (v *DeleteTodoRequest) {
	if !p.IsSetRequest() {
		return TodoServiceDeleteTodoArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *TodoServiceDeleteTodoArgs) SetRequest(val *DeleteTodoRequest) {
	p.Request = val
}

func (p *TodoServiceDeleteTodoArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *TodoServiceDeleteTodoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TodoServiceDeleteTodoArgs(%+v)", *p)
}

var fieldIDToName_TodoServiceDeleteTodoArgs = map[int16]string{
	1: "request",
}

type TodoServiceDeleteTodoResult struct {
	Success *DeleteTodoResponse `thrift:"success,0,optional" frugal:"0,optional,DeleteTodoResponse" json:"success,omitempty"`
}

func NewTodoServiceDeleteTodoResult() *TodoServiceDeleteTodoResult {
	return &TodoServiceDeleteTodoResult{}
}

func (p *TodoServiceDeleteTodoResult) InitDefault() {
}

var TodoServiceDeleteTodoResult_Success_DEFAULT *DeleteTodoResponse

func (p *TodoServiceDeleteTodoResult) GetSuccess() (v *DeleteTodoResponse) {
	if !p.IsSetSuccess() {
		return TodoServiceDeleteTodoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TodoServiceDeleteTodoResult) SetSuccess(x interface{}) {
	p.Success = x.(*DeleteTodoResponse)
}

func (p *TodoServiceDeleteTodoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TodoServiceDeleteTodoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TodoServiceDeleteTodoResult(%+v)", *p)
}

var fieldIDToName_TodoServiceDeleteTodoResult = map[int16]string{
	0: "success",
}

type TodoServiceUpdateTodoArgs struct {
	Request *UpdateTodoRequest `thrift:"request,1" frugal:"1,default,UpdateTodoRequest" json:"request"`
}

func NewTodoServiceUpdateTodoArgs() *TodoServiceUpdateTodoArgs {
	return &TodoServiceUpdateTodoArgs{}
}

func (p *TodoServiceUpdateTodoArgs) InitDefault() {
}

var TodoServiceUpdateTodoArgs_Request_DEFAULT *UpdateTodoRequest

func (p *TodoServiceUpdateTodoArgs) GetRequest() (v *UpdateTodoRequest) {
	if !p.IsSetRequest() {
		return TodoServiceUpdateTodoArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *TodoServiceUpdateTodoArgs) SetRequest(val *UpdateTodoRequest) {
	p.Request = val
}

func (p *TodoServiceUpdateTodoArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *TodoServiceUpdateTodoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TodoServiceUpdateTodoArgs(%+v)", *p)
}

var fieldIDToName_TodoServiceUpdateTodoArgs = map[int16]string{
	1: "request",
}

type TodoServiceUpdateTodoResult struct {
	Success *UpdateTodoResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateTodoResponse" json:"success,omitempty"`
}

func NewTodoServiceUpdateTodoResult() *TodoServiceUpdateTodoResult {
	return &TodoServiceUpdateTodoResult{}
}

func (p *TodoServiceUpdateTodoResult) InitDefault() {
}

var TodoServiceUpdateTodoResult_Success_DEFAULT *UpdateTodoResponse

func (p *TodoServiceUpdateTodoResult) GetSuccess() (v *UpdateTodoResponse) {
	if !p.IsSetSuccess() {
		return TodoServiceUpdateTodoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TodoServiceUpdateTodoResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateTodoResponse)
}

func (p *TodoServiceUpdateTodoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TodoServiceUpdateTodoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TodoServiceUpdateTodoResult(%+v)", *p)
}

var fieldIDToName_TodoServiceUpdateTodoResult = map[int16]string{
	0: "success",
}

type TodoServiceGetTodoArgs struct {
	Request *GetTodoRequest `thrift:"request,1" frugal:"1,default,GetTodoRequest" json:"request"`
}

func NewTodoServiceGetTodoArgs() *TodoServiceGetTodoArgs {
	return &TodoServiceGetTodoArgs{}
}

func (p *TodoServiceGetTodoArgs) InitDefault() {
}

var TodoServiceGetTodoArgs_Request_DEFAULT *GetTodoRequest

func (p *TodoServiceGetTodoArgs) GetRequest() (v *GetTodoRequest) {
	if !p.IsSetRequest() {
		return TodoServiceGetTodoArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *TodoServiceGetTodoArgs) SetRequest(val *GetTodoRequest) {
	p.Request = val
}

func (p *TodoServiceGetTodoArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *TodoServiceGetTodoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TodoServiceGetTodoArgs(%+v)", *p)
}

var fieldIDToName_TodoServiceGetTodoArgs = map[int16]string{
	1: "request",
}

type TodoServiceGetTodoResult struct {
	Success *GetTodoResponse `thrift:"success,0,optional" frugal:"0,optional,GetTodoResponse" json:"success,omitempty"`
}

func NewTodoServiceGetTodoResult() *TodoServiceGetTodoResult {
	return &TodoServiceGetTodoResult{}
}

func (p *TodoServiceGetTodoResult) InitDefault() {
}

var TodoServiceGetTodoResult_Success_DEFAULT *GetTodoResponse

func (p *TodoServiceGetTodoResult) GetSuccess() (v *GetTodoResponse) {
	if !p.IsSetSuccess() {
		return TodoServiceGetTodoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TodoServiceGetTodoResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetTodoResponse)
}

func (p *TodoServiceGetTodoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TodoServiceGetTodoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TodoServiceGetTodoResult(%+v)", *p)
}

var fieldIDToName_TodoServiceGetTodoResult = map[int16]string{
	0: "success",
}

type TodoServiceListTodoArgs struct {
	Request *ListTodoRequest `thrift:"request,1" frugal:"1,default,ListTodoRequest" json:"request"`
}

func NewTodoServiceListTodoArgs() *TodoServiceListTodoArgs {
	return &TodoServiceListTodoArgs{}
}

func (p *TodoServiceListTodoArgs) InitDefault() {
}

var TodoServiceListTodoArgs_Request_DEFAULT *ListTodoRequest

func (p *TodoServiceListTodoArgs) GetRequest() (v *ListTodoRequest) {
	if !p.IsSetRequest() {
		return TodoServiceListTodoArgs_Request_DEFAULT
	}
	return p.Request
}
func (p *TodoServiceListTodoArgs) SetRequest(val *ListTodoRequest) {
	p.Request = val
}

func (p *TodoServiceListTodoArgs) IsSetRequest() bool {
	return p.Request != nil
}

func (p *TodoServiceListTodoArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TodoServiceListTodoArgs(%+v)", *p)
}

var fieldIDToName_TodoServiceListTodoArgs = map[int16]string{
	1: "request",
}

type TodoServiceListTodoResult struct {
	Success *ListTodoResponse `thrift:"success,0,optional" frugal:"0,optional,ListTodoResponse" json:"success,omitempty"`
}

func NewTodoServiceListTodoResult() *TodoServiceListTodoResult {
	return &TodoServiceListTodoResult{}
}

func (p *TodoServiceListTodoResult) InitDefault() {
}

var TodoServiceListTodoResult_Success_DEFAULT *ListTodoResponse

func (p *TodoServiceListTodoResult) GetSuccess() (v *ListTodoResponse) {
	if !p.IsSetSuccess() {
		return TodoServiceListTodoResult_Success_DEFAULT
	}
	return p.Success
}
func (p *TodoServiceListTodoResult) SetSuccess(x interface{}) {
	p.Success = x.(*ListTodoResponse)
}

func (p *TodoServiceListTodoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *TodoServiceListTodoResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TodoServiceListTodoResult(%+v)", *p)
}

var fieldIDToName_TodoServiceListTodoResult = map[int16]string{
	0: "success",
}
