// Code generated by thriftgo (0.4.3). DO NOT EDIT.

package user

import (
	"context"
	"fmt"
	"todo-list/kitex_gen/model"
)

type User struct {
	Name     string `thrift:"name,1" frugal:"1,default,string" json:"name"`
	Phone    string `thrift:"phone,2" frugal:"2,default,string" json:"phone"`
	Password string `thrift:"password,3" frugal:"3,default,string" json:"password"`
}

func NewUser() *User {
	return &User{}
}

func (p *User) InitDefault() {
}

func (p *User) GetName() (v string) {
	return p.Name
}

func (p *User) GetPhone() (v string) {
	return p.Phone
}

func (p *User) GetPassword() (v string) {
	return p.Password
}
func (p *User) SetName(val string) {
	p.Name = val
}
func (p *User) SetPhone(val string) {
	p.Phone = val
}
func (p *User) SetPassword(val string) {
	p.Password = val
}

func (p *User) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("User(%+v)", *p)
}

var fieldIDToName_User = map[int16]string{
	1: "name",
	2: "phone",
	3: "password",
}

type RegisterRequest struct {
	Name     string `thrift:"name,1" frugal:"1,default,string" json:"name"`
	Phone    string `thrift:"phone,2" frugal:"2,default,string" json:"phone"`
	Password string `thrift:"password,3" frugal:"3,default,string" json:"password"`
}

func NewRegisterRequest() *RegisterRequest {
	return &RegisterRequest{}
}

func (p *RegisterRequest) InitDefault() {
}

func (p *RegisterRequest) GetName() (v string) {
	return p.Name
}

func (p *RegisterRequest) GetPhone() (v string) {
	return p.Phone
}

func (p *RegisterRequest) GetPassword() (v string) {
	return p.Password
}
func (p *RegisterRequest) SetName(val string) {
	p.Name = val
}
func (p *RegisterRequest) SetPhone(val string) {
	p.Phone = val
}
func (p *RegisterRequest) SetPassword(val string) {
	p.Password = val
}

func (p *RegisterRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterRequest(%+v)", *p)
}

var fieldIDToName_RegisterRequest = map[int16]string{
	1: "name",
	2: "phone",
	3: "password",
}

type RegisterResponse struct {
	Base   *model.RespBase `thrift:"base,1" frugal:"1,default,model.RespBase" json:"base"`
	UserId int32           `thrift:"userId,2" frugal:"2,default,i32" json:"userId"`
}

func NewRegisterResponse() *RegisterResponse {
	return &RegisterResponse{}
}

func (p *RegisterResponse) InitDefault() {
}

var RegisterResponse_Base_DEFAULT *model.RespBase

func (p *RegisterResponse) GetBase() (v *model.RespBase) {
	if !p.IsSetBase() {
		return RegisterResponse_Base_DEFAULT
	}
	return p.Base
}

func (p *RegisterResponse) GetUserId() (v int32) {
	return p.UserId
}
func (p *RegisterResponse) SetBase(val *model.RespBase) {
	p.Base = val
}
func (p *RegisterResponse) SetUserId(val int32) {
	p.UserId = val
}

func (p *RegisterResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *RegisterResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("RegisterResponse(%+v)", *p)
}

var fieldIDToName_RegisterResponse = map[int16]string{
	1: "base",
	2: "userId",
}

type LoginRequest struct {
	Name     string `thrift:"name,1" frugal:"1,default,string" json:"name"`
	Password string `thrift:"password,2" frugal:"2,default,string" json:"password"`
}

func NewLoginRequest() *LoginRequest {
	return &LoginRequest{}
}

func (p *LoginRequest) InitDefault() {
}

func (p *LoginRequest) GetName() (v string) {
	return p.Name
}

func (p *LoginRequest) GetPassword() (v string) {
	return p.Password
}
func (p *LoginRequest) SetName(val string) {
	p.Name = val
}
func (p *LoginRequest) SetPassword(val string) {
	p.Password = val
}

func (p *LoginRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginRequest(%+v)", *p)
}

var fieldIDToName_LoginRequest = map[int16]string{
	1: "name",
	2: "password",
}

type LoginResponse struct {
	Base *model.RespBase `thrift:"base,1" frugal:"1,default,model.RespBase" json:"base"`
	Info *model.UserInfo `thrift:"info,2" frugal:"2,default,model.UserInfo" json:"info"`
}

func NewLoginResponse() *LoginResponse {
	return &LoginResponse{}
}

func (p *LoginResponse) InitDefault() {
}

var LoginResponse_Base_DEFAULT *model.RespBase

func (p *LoginResponse) GetBase() (v *model.RespBase) {
	if !p.IsSetBase() {
		return LoginResponse_Base_DEFAULT
	}
	return p.Base
}

var LoginResponse_Info_DEFAULT *model.UserInfo

func (p *LoginResponse) GetInfo() (v *model.UserInfo) {
	if !p.IsSetInfo() {
		return LoginResponse_Info_DEFAULT
	}
	return p.Info
}
func (p *LoginResponse) SetBase(val *model.RespBase) {
	p.Base = val
}
func (p *LoginResponse) SetInfo(val *model.UserInfo) {
	p.Info = val
}

func (p *LoginResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *LoginResponse) IsSetInfo() bool {
	return p.Info != nil
}

func (p *LoginResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("LoginResponse(%+v)", *p)
}

var fieldIDToName_LoginResponse = map[int16]string{
	1: "base",
	2: "info",
}

type GetUserRequest struct {
	UserId int32 `thrift:"userId,1" frugal:"1,default,i32" json:"userId"`
}

func NewGetUserRequest() *GetUserRequest {
	return &GetUserRequest{}
}

func (p *GetUserRequest) InitDefault() {
}

func (p *GetUserRequest) GetUserId() (v int32) {
	return p.UserId
}
func (p *GetUserRequest) SetUserId(val int32) {
	p.UserId = val
}

func (p *GetUserRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserRequest(%+v)", *p)
}

var fieldIDToName_GetUserRequest = map[int16]string{
	1: "userId",
}

type GetUserResponse struct {
	Info *model.UserInfo `thrift:"info,1" frugal:"1,default,model.UserInfo" json:"info"`
	Base *model.RespBase `thrift:"base,2" frugal:"2,default,model.RespBase" json:"base"`
}

func NewGetUserResponse() *GetUserResponse {
	return &GetUserResponse{}
}

func (p *GetUserResponse) InitDefault() {
}

var GetUserResponse_Info_DEFAULT *model.UserInfo

func (p *GetUserResponse) GetInfo() (v *model.UserInfo) {
	if !p.IsSetInfo() {
		return GetUserResponse_Info_DEFAULT
	}
	return p.Info
}

var GetUserResponse_Base_DEFAULT *model.RespBase

func (p *GetUserResponse) GetBase() (v *model.RespBase) {
	if !p.IsSetBase() {
		return GetUserResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *GetUserResponse) SetInfo(val *model.UserInfo) {
	p.Info = val
}
func (p *GetUserResponse) SetBase(val *model.RespBase) {
	p.Base = val
}

func (p *GetUserResponse) IsSetInfo() bool {
	return p.Info != nil
}

func (p *GetUserResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *GetUserResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("GetUserResponse(%+v)", *p)
}

var fieldIDToName_GetUserResponse = map[int16]string{
	1: "info",
	2: "base",
}

type UpdateusernameRequest struct {
	UserId   int32  `thrift:"userId,1" frugal:"1,default,i32" json:"userId"`
	Username string `thrift:"username,2" frugal:"2,default,string" json:"username"`
}

func NewUpdateusernameRequest() *UpdateusernameRequest {
	return &UpdateusernameRequest{}
}

func (p *UpdateusernameRequest) InitDefault() {
}

func (p *UpdateusernameRequest) GetUserId() (v int32) {
	return p.UserId
}

func (p *UpdateusernameRequest) GetUsername() (v string) {
	return p.Username
}
func (p *UpdateusernameRequest) SetUserId(val int32) {
	p.UserId = val
}
func (p *UpdateusernameRequest) SetUsername(val string) {
	p.Username = val
}

func (p *UpdateusernameRequest) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateusernameRequest(%+v)", *p)
}

var fieldIDToName_UpdateusernameRequest = map[int16]string{
	1: "userId",
	2: "username",
}

type UpdateusernameResponse struct {
	Base *model.RespBase `thrift:"base,1" frugal:"1,default,model.RespBase" json:"base"`
}

func NewUpdateusernameResponse() *UpdateusernameResponse {
	return &UpdateusernameResponse{}
}

func (p *UpdateusernameResponse) InitDefault() {
}

var UpdateusernameResponse_Base_DEFAULT *model.RespBase

func (p *UpdateusernameResponse) GetBase() (v *model.RespBase) {
	if !p.IsSetBase() {
		return UpdateusernameResponse_Base_DEFAULT
	}
	return p.Base
}
func (p *UpdateusernameResponse) SetBase(val *model.RespBase) {
	p.Base = val
}

func (p *UpdateusernameResponse) IsSetBase() bool {
	return p.Base != nil
}

func (p *UpdateusernameResponse) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UpdateusernameResponse(%+v)", *p)
}

var fieldIDToName_UpdateusernameResponse = map[int16]string{
	1: "base",
}

type UserService interface {
	Register(ctx context.Context, req *RegisterRequest) (r *RegisterResponse, err error)

	Login(ctx context.Context, req *LoginRequest) (r *LoginResponse, err error)

	GetUser(ctx context.Context, req *GetUserRequest) (r *GetUserResponse, err error)

	Updateusername(ctx context.Context, req *UpdateusernameRequest) (r *UpdateusernameResponse, err error)
}

type UserServiceRegisterArgs struct {
	Req *RegisterRequest `thrift:"req,1" frugal:"1,default,RegisterRequest" json:"req"`
}

func NewUserServiceRegisterArgs() *UserServiceRegisterArgs {
	return &UserServiceRegisterArgs{}
}

func (p *UserServiceRegisterArgs) InitDefault() {
}

var UserServiceRegisterArgs_Req_DEFAULT *RegisterRequest

func (p *UserServiceRegisterArgs) GetReq() (v *RegisterRequest) {
	if !p.IsSetReq() {
		return UserServiceRegisterArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceRegisterArgs) SetReq(val *RegisterRequest) {
	p.Req = val
}

func (p *UserServiceRegisterArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceRegisterArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterArgs(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterArgs = map[int16]string{
	1: "req",
}

type UserServiceRegisterResult struct {
	Success *RegisterResponse `thrift:"success,0,optional" frugal:"0,optional,RegisterResponse" json:"success,omitempty"`
}

func NewUserServiceRegisterResult() *UserServiceRegisterResult {
	return &UserServiceRegisterResult{}
}

func (p *UserServiceRegisterResult) InitDefault() {
}

var UserServiceRegisterResult_Success_DEFAULT *RegisterResponse

func (p *UserServiceRegisterResult) GetSuccess() (v *RegisterResponse) {
	if !p.IsSetSuccess() {
		return UserServiceRegisterResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceRegisterResult) SetSuccess(x interface{}) {
	p.Success = x.(*RegisterResponse)
}

func (p *UserServiceRegisterResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceRegisterResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceRegisterResult(%+v)", *p)
}

var fieldIDToName_UserServiceRegisterResult = map[int16]string{
	0: "success",
}

type UserServiceLoginArgs struct {
	Req *LoginRequest `thrift:"req,1" frugal:"1,default,LoginRequest" json:"req"`
}

func NewUserServiceLoginArgs() *UserServiceLoginArgs {
	return &UserServiceLoginArgs{}
}

func (p *UserServiceLoginArgs) InitDefault() {
}

var UserServiceLoginArgs_Req_DEFAULT *LoginRequest

func (p *UserServiceLoginArgs) GetReq() (v *LoginRequest) {
	if !p.IsSetReq() {
		return UserServiceLoginArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceLoginArgs) SetReq(val *LoginRequest) {
	p.Req = val
}

func (p *UserServiceLoginArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceLoginArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginArgs(%+v)", *p)
}

var fieldIDToName_UserServiceLoginArgs = map[int16]string{
	1: "req",
}

type UserServiceLoginResult struct {
	Success *LoginResponse `thrift:"success,0,optional" frugal:"0,optional,LoginResponse" json:"success,omitempty"`
}

func NewUserServiceLoginResult() *UserServiceLoginResult {
	return &UserServiceLoginResult{}
}

func (p *UserServiceLoginResult) InitDefault() {
}

var UserServiceLoginResult_Success_DEFAULT *LoginResponse

func (p *UserServiceLoginResult) GetSuccess() (v *LoginResponse) {
	if !p.IsSetSuccess() {
		return UserServiceLoginResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceLoginResult) SetSuccess(x interface{}) {
	p.Success = x.(*LoginResponse)
}

func (p *UserServiceLoginResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceLoginResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceLoginResult(%+v)", *p)
}

var fieldIDToName_UserServiceLoginResult = map[int16]string{
	0: "success",
}

type UserServiceGetUserArgs struct {
	Req *GetUserRequest `thrift:"req,1" frugal:"1,default,GetUserRequest" json:"req"`
}

func NewUserServiceGetUserArgs() *UserServiceGetUserArgs {
	return &UserServiceGetUserArgs{}
}

func (p *UserServiceGetUserArgs) InitDefault() {
}

var UserServiceGetUserArgs_Req_DEFAULT *GetUserRequest

func (p *UserServiceGetUserArgs) GetReq() (v *GetUserRequest) {
	if !p.IsSetReq() {
		return UserServiceGetUserArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceGetUserArgs) SetReq(val *GetUserRequest) {
	p.Req = val
}

func (p *UserServiceGetUserArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceGetUserArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserArgs(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserArgs = map[int16]string{
	1: "req",
}

type UserServiceGetUserResult struct {
	Success *GetUserResponse `thrift:"success,0,optional" frugal:"0,optional,GetUserResponse" json:"success,omitempty"`
}

func NewUserServiceGetUserResult() *UserServiceGetUserResult {
	return &UserServiceGetUserResult{}
}

func (p *UserServiceGetUserResult) InitDefault() {
}

var UserServiceGetUserResult_Success_DEFAULT *GetUserResponse

func (p *UserServiceGetUserResult) GetSuccess() (v *GetUserResponse) {
	if !p.IsSetSuccess() {
		return UserServiceGetUserResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceGetUserResult) SetSuccess(x interface{}) {
	p.Success = x.(*GetUserResponse)
}

func (p *UserServiceGetUserResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceGetUserResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceGetUserResult(%+v)", *p)
}

var fieldIDToName_UserServiceGetUserResult = map[int16]string{
	0: "success",
}

type UserServiceUpdateusernameArgs struct {
	Req *UpdateusernameRequest `thrift:"req,1" frugal:"1,default,UpdateusernameRequest" json:"req"`
}

func NewUserServiceUpdateusernameArgs() *UserServiceUpdateusernameArgs {
	return &UserServiceUpdateusernameArgs{}
}

func (p *UserServiceUpdateusernameArgs) InitDefault() {
}

var UserServiceUpdateusernameArgs_Req_DEFAULT *UpdateusernameRequest

func (p *UserServiceUpdateusernameArgs) GetReq() (v *UpdateusernameRequest) {
	if !p.IsSetReq() {
		return UserServiceUpdateusernameArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *UserServiceUpdateusernameArgs) SetReq(val *UpdateusernameRequest) {
	p.Req = val
}

func (p *UserServiceUpdateusernameArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *UserServiceUpdateusernameArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateusernameArgs(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateusernameArgs = map[int16]string{
	1: "req",
}

type UserServiceUpdateusernameResult struct {
	Success *UpdateusernameResponse `thrift:"success,0,optional" frugal:"0,optional,UpdateusernameResponse" json:"success,omitempty"`
}

func NewUserServiceUpdateusernameResult() *UserServiceUpdateusernameResult {
	return &UserServiceUpdateusernameResult{}
}

func (p *UserServiceUpdateusernameResult) InitDefault() {
}

var UserServiceUpdateusernameResult_Success_DEFAULT *UpdateusernameResponse

func (p *UserServiceUpdateusernameResult) GetSuccess() (v *UpdateusernameResponse) {
	if !p.IsSetSuccess() {
		return UserServiceUpdateusernameResult_Success_DEFAULT
	}
	return p.Success
}
func (p *UserServiceUpdateusernameResult) SetSuccess(x interface{}) {
	p.Success = x.(*UpdateusernameResponse)
}

func (p *UserServiceUpdateusernameResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *UserServiceUpdateusernameResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("UserServiceUpdateusernameResult(%+v)", *p)
}

var fieldIDToName_UserServiceUpdateusernameResult = map[int16]string{
	0: "success",
}
